---
framework: mocha
preRun:
     command:
        - npm i
preMerge:
  pattern:
    - "*/index.ts"
postMerge:
  pattern:
    - "*/index.ts"
postRun:
     command:
        - node --version
version: 1.3
